### ISSUE TITLE
Add dbt-synapse to 1.7.latest

### ISSUE THREAD

**Issue by colin-rogers-dbt** [dbt-labs/dbt-core-bundles#127]
Now that [dbt-synapse](https://github.com/microsoft/dbt-synapse) supports 1.7 we want to begin including it in bundles. This ticket _only_ covers adding the adapter to requirements and does not include any further validation/testing

Acceptance Criteria:
The version has been added. If it fails for _any_ reason, stop the ticket and discuss in the channel.

**Comment by mikealfare** [comment]
Moving to blocked. Adding `dbt-synapse` to the bundle appears to require py311 to build.

**Comment by mikealfare** [comment]
This might have been a false alarm, looking further into the failure in the background of other tasks.

**Comment by mikealfare** [comment]
So the tests are passing for 1.0 through 1.7. They're failing on `main`/1.8. I don't know if it's happening because it's 1.8 or because it's installing from GitHub. The dependency called out in the error is `hatchling`, which is only used in 1.8. But it could arise from other combinations of dependencies.
